#include "../block.c"
#include "../pullpush.c"
#include "../shadouble.c"
#include "../tx.c"
#include "../varint.c"
#include <assert.h>

/* AUTOGENERATED MOCKS START */
/* Generated stub for fromwire_fail */
const void *fromwire_fail(const u8 **cursor UNNEEDED, size_t *max UNNEEDED)
{ fprintf(stderr, "fromwire_fail called!\n"); abort(); }
/* AUTOGENERATED MOCKS END */

static const char block[] =

  "000000203a7235653f8d5104a0a03d7373192a0dc91ba53ccf937796ca51e5"
  "7a3f866cc8445f69687d04d6a080dde27370ec07c9f2c3c3ad0dc3a160e9d0"
  "3126c3ac42d530433a5dd3571d1a000000001791f712ee4ea875429f1b7fd4"
  "322f669765969fd377cd82912024889fdda822f0b9adad09595a8142303575"
  "d4edf6f503960e72446526fa5317840dce3b59f8944fea4eba3780b52ee12a"
  "a86b185460378728b1aa0749f64481bf5acfff610801000000453043021f77"
  "7e1389615ff8d1fc8b490417d4bdbe780ea77932b603fc21ae5d14c3cacf02"
  "20414a9a9bcd98bfd6db9b2c4a0170579ddaf7e50b49a5a50d21f230a08781"
  "4fec0302000000000101000000000000000000000000000000000000000000"
  "0000000000000000000000ffffffff05037e460600ffffffff020000000000"
  "000000000000000000000000266a24aa21a9ed55ea2ab724835f14a822a5f5"
  "94d16324fbab769e2c377d9f69c89d95d3a04a7e0120000000000000000000"
  "00000000000000000000000000000000000000000000000000000002000000"
  "01944fea4eba3780b52ee12aa86b185460378728b1aa0749f64481bf5acfff"
  "61080100000048473044022029feb86438056c32ac4a1bf10c2f4928518ac0"
  "30347fd3d2132bbc963038582202201b5aec36c1d11ace347c174b0748548c"
  "f3560b0d4bc909d31597837608f9770b01ffffffff0b000000000000000000"
  "98f7165c03000000232103d4c9eb2a896d4492f4a30cfe5dd36d52f273bad9"
  "5f42ee81bdbaca463ca58624ac507d6202000000001976a9146c89a1a6ca2a"
  "e7c00b248bb2832d6f480f27da6888ac507d6202000000001976a914dbc519"
  "e477b777ba454dbef8d72ef05ddee4c70188ac507d6202000000001976a914"
  "dbc519e477b777ba454dbef8d72ef05ddee4c70188ac507d62020000000019"
  "76a914dbc519e477b777ba454dbef8d72ef05ddee4c70188ac507d62020000"
  "00001976a914dbc519e477b777ba454dbef8d72ef05ddee4c70188ac507d62"
  "02000000001976a914b6f603e399f673fee1ff82d27292a918f24b8e4a88ac"
  "507d6202000000001976a914e20b75e65370447c051ff69b96e01d93afc754"
  "0b88ac507d6202000000001976a9142820129a61e503e1fdecacd1133295ef"
  "51d2379a88ac507d6202000000001976a914dbc519e477b777ba454dbef8d7"
  "2ef05ddee4c70188ac0000000002000000019a5edf55536b95fd62bd29252c"
  "7e64c31a6d6ea0ba4313cfe232288c37ac942a000000006a47304402201a85"
  "f6f360db1e39af60d93e3e036ae1296ea16935f149db14e78047ae7a1ef502"
  "207a87e3c6a8856d365df06416a98e269616ec4c2f9d2cc83c77aea54a3e37"
  "9cb40121037ef6b53db72bc656eb9a774374bafaf9ccf92742df77cfec6746"
  "a51aa2b8da5efeffffff02a0860100000000001976a914e67c4fb24252779a"
  "6f5dcc1ae3afc70b12bd23d688ac403a1d48020000001976a914c0c3c70e4e"
  "e7cba7624aae8db05463cfc4a8456d88ac00000000";

STRUCTEQ_DEF(sha256_double, 0, sha);

int main(void)
{
	struct bitcoin_blkid prev;
	struct sha256_double merkle;
	struct bitcoin_txid txid, expected_txid;
	struct bitcoin_block *b;

	setup_locale();
	b = bitcoin_block_from_hex(NULL, block, strlen(block));

	assert(b);
	assert(b->hdr.version == CPU_TO_LE32(0x20000000));
	bitcoin_blkid_from_hex("c86c863f7ae551ca967793cf3ca51bc90d2a1973733da0a004518d3f6535723a", strlen("c86c863f7ae551ca967793cf3ca51bc90d2a1973733da0a004518d3f6535723a"), &prev);
	assert(bitcoin_blkid_eq(&prev, &b->hdr.prev_hash));
	hex_decode("445f69687d04d6a080dde27370ec07c9f2c3c3ad0dc3a160e9d03126c3ac42d5", strlen("445f69687d04d6a080dde27370ec07c9f2c3c3ad0dc3a160e9d03126c3ac42d5"), &merkle, sizeof(merkle));
	assert(sha256_double_eq(&merkle, &b->hdr.merkle_hash));
	assert(b->hdr.timestamp == CPU_TO_LE32(1564099376));
	assert(b->hdr.nonce == CPU_TO_LE32(0));

	assert(tal_count(b->tx) == 3);
	bitcoin_txid(b->tx[0], &txid);
	bitcoin_txid_from_hex("139e3729687b1783345e6ef707a9c44159dbf8e241fffebfd6a4ad70191acaf2",
			      strlen("139e3729687b1783345e6ef707a9c44159dbf8e241fffebfd6a4ad70191acaf2"),
			      &expected_txid);
	assert(bitcoin_txid_eq(&txid, &expected_txid));

	bitcoin_txid(b->tx[1], &txid);
	bitcoin_txid_from_hex("47f526f0de14eddfa7acdd5373c285a409b8d0e31234f4d225244cd145fff342",
			      strlen("47f526f0de14eddfa7acdd5373c285a409b8d0e31234f4d225244cd145fff342"),
			      &expected_txid);
	assert(bitcoin_txid_eq(&txid, &expected_txid));

	bitcoin_txid(b->tx[2], &txid);
	bitcoin_txid_from_hex("c3df8698aa5a83770d2f692093649c70bee0b9097265ac174cfe31b8dc7348a3",
			      strlen("c3df8698aa5a83770d2f692093649c70bee0b9097265ac174cfe31b8dc7348a3"),
			      &expected_txid);
	assert(bitcoin_txid_eq(&txid, &expected_txid));

	tal_free(b);
	return 0;
}
